/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view15695313;

/**
 *
 * @author William Rolim de Santana RGM: 1569431-3
 */
public class Secundario15694313 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Secundario15694313
     */
    public Secundario15694313() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Adobe Devanagari", 1, 14)); // NOI18N
        jLabel1.setText("Teste Label: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 220, 30);
        getContentPane().add(txt);
        txt.setBounds(180, 20, 200, 40);

        jRadioButton1.setFont(new java.awt.Font("Adobe Devanagari", 1, 14)); // NOI18N
        jRadioButton1.setText("jRadioButton1");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(30, 110, 200, 35);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(280, 100, 120, 40);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 190, 140, 50);

        setBounds(0, 0, 448, 507);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
/**
 *
 * @author William Rolim de Santana RGM: 1569431-3
 */