/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormularioPrincipal.java
 *
 * Created on 03/06/2018, 16:02:08
 */
package view;

import classes.Medicamento;
import dao.MedicamentoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Gobbato
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /** Creates new form FormularioPrincipal */
    public FormularioPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPesquisa = new javax.swing.JTextField();
        botIncluir1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoPesq = new javax.swing.JTextField();
        txtMedicamentoPesq = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        botIncluir = new javax.swing.JButton();
        botAlterar = new javax.swing.JButton();
        botExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Medicamentos");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));
        jPanel1.setLayout(null);

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPesquisa);
        txtPesquisa.setBounds(10, 20, 230, 20);

        botIncluir1.setText(">>");
        botIncluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botIncluir1ActionPerformed(evt);
            }
        });
        jPanel1.add(botIncluir1);
        botIncluir1.setBounds(250, 20, 49, 20);

        jLabel5.setText("Medicamento");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 90, 88, 14);

        txtCodigoPesq.setEnabled(false);
        jPanel1.add(txtCodigoPesq);
        txtCodigoPesq.setBounds(100, 60, 230, 20);

        txtMedicamentoPesq.setEnabled(false);
        jPanel1.add(txtMedicamentoPesq);
        txtMedicamentoPesq.setBounds(100, 90, 355, 20);

        jLabel4.setText("Código");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 60, 70, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 230, 480, 130);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        jLabel1.setText("Código");

        jLabel2.setText("Medicamento");

        botIncluir.setText("Incluir");
        botIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botIncluirActionPerformed(evt);
            }
        });

        botAlterar.setText("Alterar");
        botAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAlterarActionPerformed(evt);
            }
        });

        botExcluir.setText("Excluir");
        botExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(botIncluir)
                .addGap(18, 18, 18)
                .addComponent(botAlterar)
                .addGap(18, 18, 18)
                .addComponent(botExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botIncluir)
                    .addComponent(botAlterar)
                    .addComponent(botExcluir))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 50, 480, 150);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("CADASTRO DE MEDICAMENTOS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 10, 350, 30);

        setSize(new java.awt.Dimension(533, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void botIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botIncluirActionPerformed
        // TODO add your handling code here:
        MedicamentoDAO medInc =  new MedicamentoDAO();
        Medicamento med = new Medicamento();
        med.setComercial(txtMedicamento.getText());
        med.setCodComercial(Integer.parseInt(txtCodigo.getText()));
        if(medInc.incluirMedicamento(med)){
            JOptionPane.showMessageDialog(this, "Medicamento Inserido com Sucesso!");
        }else{
            JOptionPane.showMessageDialog(this, "Erro na Inserção do Medicamento!");    
        }
    }//GEN-LAST:event_botIncluirActionPerformed

    private void botIncluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botIncluir1ActionPerformed
        // TODO add your handling code here:
        int cod_comercial;
        Medicamento med;
        cod_comercial = Integer.parseInt(txtPesquisa.getText());
        med = new MedicamentoDAO().getMedicamento(cod_comercial);
        if(med==null){
            JOptionPane.showMessageDialog(this, "Não Existe Código cadastrado!");
        }else{
            txtCodigoPesq.setText(""+med.getCodComercial());
            txtMedicamentoPesq.setText(med.getComercial());
        }
    }//GEN-LAST:event_botIncluir1ActionPerformed

    private void botAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAlterarActionPerformed
        // TODO add your handling code here:
        Medicamento med;
        int cod_comercial = Integer.parseInt(txtCodigo.getText());
        String comercial = txtMedicamento.getText();
        med = new Medicamento();
        med.setCodComercial(cod_comercial);
        med.setComercial(comercial);
        JOptionPane.showMessageDialog(this, new MedicamentoDAO().alterarMedicamento(med));
        //med = new MedicamentoDAO().getMedicamento(cod_comercial);
    }//GEN-LAST:event_botAlterarActionPerformed

    private void botExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botExcluirActionPerformed
        // TODO add your handling code here:
        Medicamento med;
        int cod_comercial = Integer.parseInt(txtCodigo.getText());
        med = new Medicamento();
        med.setCodComercial(cod_comercial);
        JOptionPane.showMessageDialog(this, new MedicamentoDAO().excluirMedicamento(med));
    }//GEN-LAST:event_botExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAlterar;
    private javax.swing.JButton botExcluir;
    private javax.swing.JButton botIncluir;
    private javax.swing.JButton botIncluir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoPesq;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextField txtMedicamentoPesq;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
