/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medialuno;

import javax.swing.JOptionPane;

/**
 *
 * @author willi
 */
public class MediaAluno extends javax.swing.JFrame {

    private String nome;
    private Float provaParcial;
    private Float provaRegimental;
    private Float trabalhos;
    private Float projeto;
    private String resultado;

    public MediaAluno() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMediaFinal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        txtTrabalhos = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtProvaParcial = new javax.swing.JTextField();
        txtProjeto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRegimental = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        lblMediaFinal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMediaFinal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblMediaFinal);
        lblMediaFinal.setBounds(20, 260, 360, 110);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 29, 70, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Prova Parcial:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 60, 100, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Projeto:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 90, 100, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Trabalhos:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 120, 100, 15);

        btnLimpar.setBackground(new java.awt.Color(0, 51, 153));
        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar);
        btnLimpar.setBounds(240, 200, 130, 30);

        btnCalcular.setBackground(new java.awt.Color(0, 51, 153));
        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular);
        btnCalcular.setBounds(20, 200, 130, 30);

        txtTrabalhos.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtTrabalhos);
        txtTrabalhos.setBounds(130, 110, 240, 30);

        txtNome.setBackground(new java.awt.Color(204, 255, 255));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome);
        txtNome.setBounds(130, 20, 240, 30);

        txtProvaParcial.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtProvaParcial);
        txtProvaParcial.setBounds(130, 50, 240, 30);

        txtProjeto.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtProjeto);
        txtProjeto.setBounds(130, 80, 240, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Regimental:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 150, 100, 15);

        txtRegimental.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtRegimental);
        txtRegimental.setBounds(130, 140, 240, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 380);

        setSize(new java.awt.Dimension(415, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try {
            if (txtNome.getText().trim().equals("")) {
                txtNome.setText("Preencha o Campo Nome");
            }
            if (txtProvaParcial.getText().trim().equals("")) {
                txtProvaParcial.setText("Preencha o Campo prova parcial");
            }
            if (txtProjeto.getText().trim().equals("")) {
                txtProjeto.setText("Preencha o Campo projeto");
            }
            if (txtTrabalhos.getText().trim().equals("")) {
                txtTrabalhos.setText("Preencha o trabalho");
            }
            if (txtRegimental.getText().trim().equals("")) {
                txtRegimental.setText("Preencha o Campo Prova Regimental");

            } else {
                nome = txtNome.getText();
                provaParcial = Float.parseFloat(txtProvaParcial.getText());
                provaRegimental = Float.parseFloat(txtRegimental.getText());
                trabalhos = Float.parseFloat(txtTrabalhos.getText());
                projeto = Float.parseFloat(txtProjeto.getText());

                double media = 0;
                media = 0.2 * provaParcial + 0.4 * provaRegimental + 0.2 * projeto + 0.2 * trabalhos;
                if (media >= 6) {
                    resultado = "Aprovado";
                } else if ((media >= 3) && (media < 6)) {
                    resultado = "Recuperação";
                } else {
                    resultado = "Reprovado";
                }

                lblMediaFinal.setText("<html>" + "Nome: " + nome + "<br/>" + "\n Media: " + media + "<br/>" + "\n Resultado:" + resultado + "</html>");
            }
        } catch (Exception e) {
            System.out.println("Algo inesperado aconteceu");
        }

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNome.setText(null);
        txtProjeto.setText(null);
        txtProvaParcial.setText(null);
        txtRegimental.setText(null);
        txtTrabalhos.setText(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MediaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MediaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MediaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MediaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MediaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMediaFinal;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtProjeto;
    private javax.swing.JTextField txtProvaParcial;
    private javax.swing.JTextField txtRegimental;
    private javax.swing.JTextField txtTrabalhos;
    // End of variables declaration//GEN-END:variables
}
