/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.DespesasBean;
import classes.Despesa;

/**
 *
 * @author willi
 */
public class Contas extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Contas() {
        initComponents();
    }

    private Despesa montaDespesa() {
        Despesa despesa = new Despesa();

        despesa.setValor1(Float.parseFloat(txtD_V1.getText()));
        despesa.setValor2(Float.parseFloat(txtD_V2.getText()));
        despesa.setValor3(Float.parseFloat(txtD_V3.getText()));

        if (rbtEmpresa.isSelected()) {
            despesa.setTipoEmpresa("E");
        } else {
            despesa.setTipoEmpresa("S");
        }

        if (cmbTributo.getSelectedItem().equals("Simples Nacional")) {
            despesa.setOpcaoTributaria("SN");
        } else {
            despesa.setOpcaoTributaria("LR");
        }

        return despesa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtValorFinal = new javax.swing.JTextField();
        txtD_V1 = new javax.swing.JTextField();
        txtD_V2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtD_V3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtD_Total = new javax.swing.JTextField();
        rbtEmpresa = new javax.swing.JRadioButton();
        rbtSociedade = new javax.swing.JRadioButton();
        cmbTributo = new javax.swing.JComboBox<>();
        botCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Valor Final:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(16, 200, 60, 14);

        jLabel2.setText("V1:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 30, 20, 14);

        jLabel3.setText("V2:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 70, 16, 14);
        getContentPane().add(txtValorFinal);
        txtValorFinal.setBounds(80, 190, 150, 30);
        getContentPane().add(txtD_V1);
        txtD_V1.setBounds(80, 20, 150, 30);
        getContentPane().add(txtD_V2);
        txtD_V2.setBounds(80, 60, 150, 30);

        jLabel4.setText("V3:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 100, 16, 14);
        getContentPane().add(txtD_V3);
        txtD_V3.setBounds(80, 100, 150, 30);

        jLabel5.setText("TOTAL:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(16, 150, 50, 14);
        getContentPane().add(txtD_Total);
        txtD_Total.setBounds(80, 150, 150, 30);

        buttonGroup1.add(rbtEmpresa);
        rbtEmpresa.setText("EI");
        rbtEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(rbtEmpresa);
        rbtEmpresa.setBounds(340, 30, 170, 23);

        buttonGroup1.add(rbtSociedade);
        rbtSociedade.setText("LR");
        rbtSociedade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSociedadeActionPerformed(evt);
            }
        });
        getContentPane().add(rbtSociedade);
        rbtSociedade.setBounds(340, 70, 110, 23);

        cmbTributo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simples Nacional", "Lucro Real" }));
        getContentPane().add(cmbTributo);
        cmbTributo.setBounds(380, 130, 150, 20);

        botCalcular.setText("Calcular");
        botCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(botCalcular);
        botCalcular.setBounds(360, 183, 130, 40);

        setSize(new java.awt.Dimension(600, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEmpresaActionPerformed
        // TODO add your handling code here:
        float valorTotal = new DespesasBean().calculaValorTotal(montaDespesa());
        txtD_Total.setText(valorTotal + "");
    }//GEN-LAST:event_rbtEmpresaActionPerformed

    private void botCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCalcularActionPerformed
        float valorFinal = new DespesasBean().calculaValorFinal(montaDespesa());
        txtValorFinal.setText(valorFinal + "");
    }//GEN-LAST:event_botCalcularActionPerformed

    private void rbtSociedadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSociedadeActionPerformed
        // TODO add your handling code here:
        float valorTotal = new DespesasBean().calculaValorTotal(montaDespesa());
        txtD_Total.setText(valorTotal + "");
    }//GEN-LAST:event_rbtSociedadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botCalcular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbTributo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton rbtEmpresa;
    private javax.swing.JRadioButton rbtSociedade;
    private javax.swing.JTextField txtD_Total;
    private javax.swing.JTextField txtD_V1;
    private javax.swing.JTextField txtD_V2;
    private javax.swing.JTextField txtD_V3;
    private javax.swing.JTextField txtValorFinal;
    // End of variables declaration//GEN-END:variables
}
