/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author willi
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }
    private float v1;
    private String sinal;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        btnZero = new javax.swing.JToggleButton();
        btnUm = new javax.swing.JToggleButton();
        btnDois = new javax.swing.JToggleButton();
        btnTreis = new javax.swing.JToggleButton();
        btnQuatro = new javax.swing.JToggleButton();
        btnCinco = new javax.swing.JToggleButton();
        btnSeis = new javax.swing.JToggleButton();
        btnSete = new javax.swing.JToggleButton();
        btnOito = new javax.swing.JToggleButton();
        btnVirgula = new javax.swing.JToggleButton();
        btnDividir = new javax.swing.JToggleButton();
        btnNove = new javax.swing.JToggleButton();
        btnIgual = new javax.swing.JToggleButton();
        btnApagar = new javax.swing.JToggleButton();
        btnVezes = new javax.swing.JToggleButton();
        btnMais = new javax.swing.JToggleButton();
        btnMenos = new javax.swing.JToggleButton();
        btnExcluir = new javax.swing.JToggleButton();
        txtTotal = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem13 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(null);

        btnZero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnZero.setText("0");
        jPanel1.add(btnZero);
        btnZero.setBounds(20, 290, 110, 40);

        btnUm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUm.setText("1");
        btnUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmActionPerformed(evt);
            }
        });
        jPanel1.add(btnUm);
        btnUm.setBounds(20, 240, 50, 40);

        btnDois.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDois.setText("2");
        btnDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoisActionPerformed(evt);
            }
        });
        jPanel1.add(btnDois);
        btnDois.setBounds(80, 240, 50, 40);

        btnTreis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTreis.setText("3");
        btnTreis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreisActionPerformed(evt);
            }
        });
        jPanel1.add(btnTreis);
        btnTreis.setBounds(140, 240, 50, 40);

        btnQuatro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQuatro.setText("4");
        btnQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuatroActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuatro);
        btnQuatro.setBounds(20, 190, 50, 40);

        btnCinco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCinco.setText("5");
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCinco);
        btnCinco.setBounds(80, 190, 50, 40);

        btnSeis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSeis.setText("6");
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeis);
        btnSeis.setBounds(140, 190, 50, 40);

        btnSete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSete.setText("7");
        btnSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSete);
        btnSete.setBounds(20, 140, 50, 40);

        btnOito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOito.setText("8");
        jPanel1.add(btnOito);
        btnOito.setBounds(80, 140, 50, 40);

        btnVirgula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVirgula.setText(".");
        jPanel1.add(btnVirgula);
        btnVirgula.setBounds(140, 290, 50, 40);

        btnDividir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDividir.setText("/");
        jPanel1.add(btnDividir);
        btnDividir.setBounds(200, 290, 50, 40);

        btnNove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNove.setText("9");
        jPanel1.add(btnNove);
        btnNove.setBounds(140, 140, 50, 40);

        btnIgual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIgual.setText("=");
        jPanel1.add(btnIgual);
        btnIgual.setBounds(260, 240, 50, 90);

        btnApagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnApagar.setText("A");
        jPanel1.add(btnApagar);
        btnApagar.setBounds(260, 140, 50, 40);

        btnVezes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVezes.setText("*");
        jPanel1.add(btnVezes);
        btnVezes.setBounds(200, 240, 50, 40);

        btnMais.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMais.setText("+");
        jPanel1.add(btnMais);
        btnMais.setBounds(200, 140, 50, 40);

        btnMenos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMenos.setText("-");
        jPanel1.add(btnMenos);
        btnMenos.setBounds(200, 190, 50, 40);

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluir.setText("E");
        jPanel1.add(btnExcluir);
        btnExcluir.setBounds(260, 190, 50, 40);

        txtTotal.setBackground(new java.awt.Color(0, 204, 204));
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtTotal);
        txtTotal.setBounds(20, 20, 290, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 330, 360);

        jMenu2.setText("Exibir");

        jMenuItem1.setText("Padrão");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Cientifica");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Programador");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Estatistica");
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator1);

        jMenuItem5.setText("Histórico");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Agrupamento De Digitos");
        jMenu2.add(jMenuItem6);
        jMenu2.add(jSeparator2);

        jMenuItem7.setText("Basico");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Conversão de unidades");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Calculo de datas");
        jMenu2.add(jMenuItem9);

        jMenu5.setText("Planilhas");
        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Editar");

        jMenuItem10.setText("Copiar");
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Colar");
        jMenu3.add(jMenuItem11);
        jMenu3.add(jSeparator3);

        jMenu6.setText("Histórico");
        jMenu3.add(jMenu6);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");

        jMenuItem12.setText("Exibir Ajuda");
        jMenu4.add(jMenuItem12);
        jMenu4.add(jSeparator4);

        jMenuItem13.setText("Sobre a Calculadora");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(348, 417));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        Sobre s = new Sobre();
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void btnUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmActionPerformed
        txtTotal.setText("1");
        float um = 1;
    }//GEN-LAST:event_btnUmActionPerformed

    private void btnDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoisActionPerformed
        txtTotal.setText("2");
        float dois = 2;
    }//GEN-LAST:event_btnDoisActionPerformed

    private void btnTreisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreisActionPerformed
        // TODO add your handling code here:
        txtTotal.setText("3");
        float tres = 3;
    }//GEN-LAST:event_btnTreisActionPerformed

    private void btnQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuatroActionPerformed
        txtTotal.setText("4");
        float tres = 4;
    }//GEN-LAST:event_btnQuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        txtTotal.setText("5");
        float cinco = 5;
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
        txtTotal.setText("6");
        float seis = 6;
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeteActionPerformed
        txtTotal.setText("7");
        float sete = 7;
    }//GEN-LAST:event_btnSeteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnApagar;
    private javax.swing.JToggleButton btnCinco;
    private javax.swing.JToggleButton btnDividir;
    private javax.swing.JToggleButton btnDois;
    private javax.swing.JToggleButton btnExcluir;
    private javax.swing.JToggleButton btnIgual;
    private javax.swing.JToggleButton btnMais;
    private javax.swing.JToggleButton btnMenos;
    private javax.swing.JToggleButton btnNove;
    private javax.swing.JToggleButton btnOito;
    private javax.swing.JToggleButton btnQuatro;
    private javax.swing.JToggleButton btnSeis;
    private javax.swing.JToggleButton btnSete;
    private javax.swing.JToggleButton btnTreis;
    private javax.swing.JToggleButton btnUm;
    private javax.swing.JToggleButton btnVezes;
    private javax.swing.JToggleButton btnVirgula;
    private javax.swing.JToggleButton btnZero;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
