/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view15694313;

import classes15694313.Dados15694313;
import bean15694313.FreteBean15694313;

/**
 *
 * @author logonaf
 */
public class Frete15694313 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Sobre15694313
     */
    public Frete15694313() {
        initComponents();
    }

    // a cada 10 kilos 1.50 20 kilos 3.50
    public Dados15694313 dados() {
        Dados15694313 dados = new Dados15694313();
        if (lstEstados.getSelectedItem().equals("São Paulo")) {
            dados.setEstado("São Paulo");
        } else if (lstEstados.getSelectedItem().equals("Rio de Janeiro")) {
            dados.setEstado("Rio de Janeiro");
        }
        else if (lstEstados.getSelectedItem().equals("Minas Gerais")) {
            dados.setEstado("Minas Gerais");
        } else if (lstEstados.getSelectedItem().equals("Espirito Santo")) {
            dados.setEstado("Espirito Santo");
        }
        dados.setPeso(Double.parseDouble(txtPeso.getText()));
        
        
        if (chkSedex.isSelected()) {
            dados.setEncomenda("Sedex");
        } else if (chkAR.isSelected()) {
            dados.setEncomenda("AR");
        }
        if (chkSimples.isSelected()) {
            dados.setEncomenda("Simples");
        }
        if (chkDinheiro.isSelected()) {
            dados.setPagamento("Dinheiro");
        } else if (chkCheque.isSelected()) {
            dados.setPagamento("Cheque");
        }
         if (chkCartaoDeCredito.isSelected() ) {
            dados.setPagamento("Cartão");
        }

        return dados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEncomenda = new javax.swing.ButtonGroup();
        buttonGroupPagamento = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lstEstados = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        chkSimples = new javax.swing.JRadioButton();
        chkDinheiro = new javax.swing.JRadioButton();
        chkCartaoDeCredito = new javax.swing.JRadioButton();
        chkSedex = new javax.swing.JRadioButton();
        chkAR = new javax.swing.JRadioButton();
        chkCheque = new javax.swing.JRadioButton();
        btnFechar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("Pagamento");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 180, 200, 50);

        lstEstados.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lstEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "São Paulo", "Rio de Janeiro", "Minas Gerais", "Espirito Santo" }));
        getContentPane().add(lstEstados);
        lstEstados.setBounds(30, 50, 190, 32);

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Estado:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 0, 360, 50);
        getContentPane().add(txtTotal);
        txtTotal.setBounds(30, 420, 310, 30);

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("Total:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 380, 360, 50);

        buttonGroupEncomenda.add(chkSimples);
        chkSimples.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        chkSimples.setText("Simples");
        getContentPane().add(chkSimples);
        chkSimples.setBounds(20, 290, 120, 23);

        buttonGroupPagamento.add(chkDinheiro);
        chkDinheiro.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        chkDinheiro.setText("Dinheiro");
        getContentPane().add(chkDinheiro);
        chkDinheiro.setBounds(220, 220, 160, 35);

        buttonGroupPagamento.add(chkCartaoDeCredito);
        chkCartaoDeCredito.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        chkCartaoDeCredito.setText("Cartão de Credito");
        getContentPane().add(chkCartaoDeCredito);
        chkCartaoDeCredito.setBounds(220, 290, 230, 23);

        buttonGroupEncomenda.add(chkSedex);
        chkSedex.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        chkSedex.setText("Sedex");
        getContentPane().add(chkSedex);
        chkSedex.setBounds(20, 220, 91, 35);

        buttonGroupEncomenda.add(chkAR);
        chkAR.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        chkAR.setText("A.R");
        getContentPane().add(chkAR);
        chkAR.setBounds(20, 260, 93, 23);

        buttonGroupPagamento.add(chkCheque);
        chkCheque.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        chkCheque.setText("Cheque");
        getContentPane().add(chkCheque);
        chkCheque.setBounds(220, 260, 130, 23);

        btnFechar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar);
        btnFechar.setBounds(250, 340, 170, 40);

        btnCalcular.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(30, 340, 160, 40);

        jLabel4.setBackground(new java.awt.Color(0, 51, 51));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setText("Peso:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 90, 360, 50);
        getContentPane().add(txtPeso);
        txtPeso.setBounds(20, 140, 310, 30);

        jLabel5.setBackground(new java.awt.Color(0, 51, 51));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setText("Tipo Encomenda:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 180, 200, 50);

        setBounds(0, 0, 463, 515);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if (txtPeso.getText().trim().equals("")) {
            txtPeso.setText("Digite o valor do Peso");
        } else {
            double total = 0;
            total = new FreteBean15694313().CalculoFreteTotal(dados());
            txtTotal.setText("R$: " + total);
        }


    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.hide();
    }//GEN-LAST:event_btnFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnFechar;
    private javax.swing.ButtonGroup buttonGroupEncomenda;
    private javax.swing.ButtonGroup buttonGroupPagamento;
    private javax.swing.JRadioButton chkAR;
    private javax.swing.JRadioButton chkCartaoDeCredito;
    private javax.swing.JRadioButton chkCheque;
    private javax.swing.JRadioButton chkDinheiro;
    private javax.swing.JRadioButton chkSedex;
    private javax.swing.JRadioButton chkSimples;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> lstEstados;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
