/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.NrRgm_Frete;
import bean.NrRgm_FreteBean;

/**
 *
 * @author Alexander
 */
public class NrRgm_CalculoFrete extends javax.swing.JInternalFrame {

    /**
     * Creates new form NrRgm_Frete
     */
    public NrRgm_CalculoFrete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();

        setClosable(true);
        setTitle("Cálculo de Frete - NrRgm");
        getContentPane().setLayout(null);

        jLabel1.setText("Pagamento:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 140, 110, 14);

        jLabel2.setText("Total a Pagar:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 270, 180, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "São Paulo", "Rio de Janeiro", "Minas Gerais", "Espiríto Santo" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(30, 40, 190, 30);

        jTextField1.setEnabled(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 290, 190, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("A.R");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(30, 180, 60, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Sedex 10");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(30, 160, 90, 23);

        jLabel3.setText("Peso:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 80, 70, 14);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Simples");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(30, 200, 93, 23);

        jLabel4.setText("Estado:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 20, 70, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(30, 100, 190, 30);

        jButton1.setText("Fechar");
        getContentPane().add(jButton1);
        jButton1.setBounds(133, 240, 80, 23);

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 240, 80, 23);

        jLabel5.setText("Tipo Encomenda:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 140, 110, 14);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Dinheiro");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(150, 160, 120, 23);

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Cheque");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(150, 180, 120, 23);

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("Cartão de Crédito");
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(150, 200, 130, 23);

        setBounds(0, 0, 306, 367);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        NrRgm_Frete frete = new NrRgm_Frete();
        String estado;
        float peso = 0f;
        float tipoencomenda = 0f;
        float pagamento= 0f;
        estado = jComboBox1.getItemAt(jComboBox1.getSelectedIndex()).toString();
        peso = Float.parseFloat(jTextField2.getText());
        
        if(jRadioButton2.isSelected()){
            tipoencomenda = 25f;
        }else if(jRadioButton1.isSelected()){
            tipoencomenda = 13.5f;
        }else if(jRadioButton3.isSelected()){
            tipoencomenda = 5.6f;
        }
        
        if(jRadioButton4.isSelected()){
            pagamento = 0f;
        }else if(jRadioButton5.isSelected()){
            pagamento = 0.1f;
        }else if(jRadioButton6.isSelected()){
            pagamento = 0.12f;
        }
        
        frete.setEstado(estado);
        frete.setPeso(peso);
        frete.setTipo(tipoencomenda);
        frete.setPagamento(pagamento);
        
        NrRgm_FreteBean freteBean = new NrRgm_FreteBean();
        
        jTextField1.setText(""+freteBean.CalculaFrete(frete));
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
