/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package venda_carros;

import java.util.Locale;
import javax.swing.JRadioButton;

/**
 *
 * @author willi
 */
public class Concecionaria extends javax.swing.JFrame {

    /**
     * Creates new form Concecionaria
     */
    private float qtd = 0;

    public Concecionaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        optELXCD = new javax.swing.JRadioButton();
        optEX = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        opt2p = new javax.swing.JRadioButton();
        opt4p = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtQTD = new javax.swing.JTextField();
        chkPagtVista = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        chkRadioCD = new javax.swing.JCheckBox();
        chkAirBag = new javax.swing.JCheckBox();
        chkArCondicionado = new javax.swing.JCheckBox();
        chkTravaEletrica = new javax.swing.JCheckBox();
        lblResultado = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JToggleButton();
        btnCalcular = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Veiculos");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(null);

        buttonGroup1.add(optELXCD);
        optELXCD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        optELXCD.setText("ELX CD");
        jPanel1.add(optELXCD);
        optELXCD.setBounds(10, 60, 93, 23);

        buttonGroup1.add(optEX);
        optEX.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        optEX.setText("EX");
        jPanel1.add(optEX);
        optEX.setBounds(10, 30, 41, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 30, 140, 100);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Portas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(null);

        buttonGroup2.add(opt2p);
        opt2p.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        opt2p.setText("2p");
        jPanel2.add(opt2p);
        opt2p.setBounds(10, 30, 41, 23);

        buttonGroup2.add(opt4p);
        opt4p.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        opt4p.setText("4p");
        jPanel2.add(opt4p);
        opt4p.setBounds(10, 60, 41, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 140, 140, 90);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Qtd:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(16, 37, 27, 15);
        jPanel3.add(txtQTD);
        txtQTD.setBounds(50, 30, 70, 30);

        chkPagtVista.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkPagtVista.setText("Pagt. a vista");
        jPanel3.add(chkPagtVista);
        chkPagtVista.setBounds(10, 70, 120, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(30, 240, 140, 110);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acessórios Opcionais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel4.setLayout(null);

        chkRadioCD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkRadioCD.setText("Radio CD");
        jPanel4.add(chkRadioCD);
        chkRadioCD.setBounds(20, 130, 140, 23);

        chkAirBag.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkAirBag.setText("Air Bag");
        jPanel4.add(chkAirBag);
        chkAirBag.setBounds(20, 40, 110, 23);

        chkArCondicionado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkArCondicionado.setText("Ar Condicionado");
        jPanel4.add(chkArCondicionado);
        chkArCondicionado.setBounds(20, 70, 140, 23);

        chkTravaEletrica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkTravaEletrica.setText("Trava Eletrica");
        jPanel4.add(chkTravaEletrica);
        chkTravaEletrica.setBounds(20, 100, 140, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(210, 30, 190, 160);

        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(lblResultado);
        lblResultado.setBounds(190, 210, 230, 140);

        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(250, 360, 150, 60);

        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(30, 360, 150, 60);

        setSize(new java.awt.Dimension(444, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        chkPagtVista.setSelected(false);
        chkAirBag.setSelected(false);
        chkArCondicionado.setSelected(false);
        chkPagtVista.setSelected(false);
        chkRadioCD.setSelected(false);
        chkTravaEletrica.setSelected(false);
        txtQTD.setText("");
        lblResultado.setText("");


    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if (!txtQTD.getText().equals(null) && !txtQTD.getText().isEmpty()) {//Veridicar se o campo está vazio

            qtd = Float.valueOf(txtQTD.getText());
        }
        float preco = 0;
        float total = 0;

        if (optEX.isSelected()) {
            preco += 14021;
        } else if (optELXCD.isSelected()) {
            preco += 15107;
        }
        if (opt2p.isSelected()) {
            preco += 16235;
        } else if (opt4p.isSelected()) {
            preco += 17450;
        }
        if (chkAirBag.isSelected()) {
            preco += 150;
        } else if (chkArCondicionado.isSelected()) {
            preco += 2170;
        }
        if (chkTravaEletrica.isSelected()) {
            preco += 400;
        } else if (chkRadioCD.isSelected()) {
            preco += 550;
        }
        if (preco == 0) {
            lblResultado.setText("Nenhuma opção Selecionada");
        } else if (!chkPagtVista.isSelected() && txtQTD.getText().isEmpty()) {
            lblResultado.setText("R$: " + preco);
        }
        if (chkPagtVista.isSelected() && txtQTD.getText().isEmpty()) {
            lblResultado.setText("R$: " + ((preco * 10) / 100));
        } else if (chkPagtVista.isSelected() && !txtQTD.getText().isEmpty()) {
            total = qtd * ((preco * 10) / 100);
            lblResultado.setText("R$: " + total);
        }
        if (!chkPagtVista.isSelected() && !txtQTD.getText().isEmpty()) {
            total = qtd * preco;
            lblResultado.setText("R$: " + total);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Concecionaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Concecionaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Concecionaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Concecionaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Concecionaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCalcular;
    private javax.swing.JToggleButton btnLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chkAirBag;
    private javax.swing.JCheckBox chkArCondicionado;
    private javax.swing.JCheckBox chkPagtVista;
    private javax.swing.JCheckBox chkRadioCD;
    private javax.swing.JCheckBox chkTravaEletrica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton opt2p;
    private javax.swing.JRadioButton opt4p;
    private javax.swing.JRadioButton optELXCD;
    private javax.swing.JRadioButton optEX;
    private javax.swing.JTextField txtQTD;
    // End of variables declaration//GEN-END:variables
}
