/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.DespesasBean;
import classes.Dados;

/**
 *
 * @author willi
 */
public class ContasAPagar extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContasAPagar2
     */
    public ContasAPagar() {
        initComponents();
    }

    private Dados dados() {
        Dados d = new Dados();

        d.setV1((Double.parseDouble(txtValor1.getText())));
        d.setV2((Double.parseDouble(txtValor2.getText())));
        d.setV3((Double.parseDouble(txtValor3.getText())));
        double empresa = 0;

        if (chkEmpresaIndividual.isSelected()) {
            d.setTipoEmpresa(0.125);// dividi-se 12.5/100 -> 0.25
        } else {
            d.setTipoEmpresa(0.153);
        }

        String opcoesTributarias;
        opcoesTributarias = cmbOpcoesTributarias.getItemAt(cmbOpcoesTributarias.getSelectedIndex()).toString();
        d.setOptTributarias(opcoesTributarias);
        return d;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoDeEmpresa = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtValor1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtValor3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValorFinal = new javax.swing.JTextField();
        chkSociedadeIndividual = new javax.swing.JRadioButton();
        chkEmpresaIndividual = new javax.swing.JRadioButton();
        cmbOpcoesTributarias = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 220, 70, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Opções Tributárias:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 180, 120, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor 2:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 110, 70, 30);

        txtValor2.setBackground(new java.awt.Color(153, 255, 255));
        txtValor2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jPanel1.add(txtValor2);
        txtValor2.setBounds(130, 110, 140, 30);

        txtTotal.setBackground(new java.awt.Color(153, 255, 255));
        txtTotal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jPanel1.add(txtTotal);
        txtTotal.setBounds(130, 220, 140, 30);

        txtValor1.setBackground(new java.awt.Color(153, 255, 255));
        txtValor1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jPanel1.add(txtValor1);
        txtValor1.setBounds(130, 70, 140, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor 3:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 150, 70, 30);

        txtValor3.setBackground(new java.awt.Color(153, 255, 255));
        txtValor3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jPanel1.add(txtValor3);
        txtValor3.setBounds(130, 150, 140, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("VF:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 290, 70, 30);

        txtValorFinal.setBackground(new java.awt.Color(153, 255, 255));
        txtValorFinal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jPanel1.add(txtValorFinal);
        txtValorFinal.setBounds(130, 290, 140, 30);

        buttonGroupTipoDeEmpresa.add(chkSociedadeIndividual);
        chkSociedadeIndividual.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        chkSociedadeIndividual.setText("Sociedade Individual");
        chkSociedadeIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSociedadeIndividualActionPerformed(evt);
            }
        });
        jPanel1.add(chkSociedadeIndividual);
        chkSociedadeIndividual.setBounds(330, 110, 190, 31);

        buttonGroupTipoDeEmpresa.add(chkEmpresaIndividual);
        chkEmpresaIndividual.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        chkEmpresaIndividual.setText("Empresa Individual");
        chkEmpresaIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEmpresaIndividualActionPerformed(evt);
            }
        });
        jPanel1.add(chkEmpresaIndividual);
        chkEmpresaIndividual.setBounds(330, 70, 190, 31);

        cmbOpcoesTributarias.setBackground(new java.awt.Color(153, 255, 255));
        cmbOpcoesTributarias.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cmbOpcoesTributarias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simples Nacional", "Lucro Real" }));
        jPanel1.add(cmbOpcoesTributarias);
        cmbOpcoesTributarias.setBounds(330, 220, 190, 30);

        btnCalcular.setBackground(new java.awt.Color(0, 51, 51));
        btnCalcular.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular);
        btnCalcular.setBounds(330, 290, 190, 40);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Valor 1:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 70, 70, 30);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Despesas:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 30, 90, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de Empresa:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(320, 30, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 550);

        setBounds(0, 0, 595, 403);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        double calculoFinal = new DespesasBean().CalculoTributarioFinal(dados());
        txtValorFinal.setText("R$: " + calculoFinal);

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void chkEmpresaIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEmpresaIndividualActionPerformed
        double calculo = new DespesasBean().CalculoTotal(dados());
        txtTotal.setText("R$: " + calculo);
    }//GEN-LAST:event_chkEmpresaIndividualActionPerformed

    private void chkSociedadeIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSociedadeIndividualActionPerformed
        double calculo = new DespesasBean().CalculoTotal(dados());
        txtTotal.setText("R$: " + calculo);
    }//GEN-LAST:event_chkSociedadeIndividualActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCalcular;
    private javax.swing.ButtonGroup buttonGroupTipoDeEmpresa;
    private javax.swing.JRadioButton chkEmpresaIndividual;
    private javax.swing.JRadioButton chkSociedadeIndividual;
    private javax.swing.JComboBox<String> cmbOpcoesTributarias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    private javax.swing.JTextField txtValor3;
    private javax.swing.JTextField txtValorFinal;
    // End of variables declaration//GEN-END:variables
}
