/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.AlunoBean;
import classe.Aluno;
import dao.AlunoDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexander
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    public Aluno montaAluno() {
        Aluno aluno = new Aluno();
        aluno.setRgm(txtRgm.getText());
        aluno.setNome(txtNome.getText());
        aluno.setNotaProvaParcial(Float.parseFloat(txtNotaParcial.getText()));
        aluno.setNotaTrabalho(Float.parseFloat(txtNotaTrabalho.getText()));
        return aluno;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNotaA1 = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtNotaTrabalho = new javax.swing.JTextField();
        txtNotaParcial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRgm = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        lblMensagem = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nota A1:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 160, 100, 14);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Aluno:");
        jLabel2.setMaximumSize(new java.awt.Dimension(43, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(43, 14));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 100, 14);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nota Trabalho:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 100, 14);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nota Parcial:");
        jLabel4.setMaximumSize(new java.awt.Dimension(43, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(43, 14));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 100, 14);
        getContentPane().add(txtNotaA1);
        txtNotaA1.setBounds(130, 150, 80, 20);
        getContentPane().add(txtNome);
        txtNome.setBounds(130, 60, 250, 20);
        getContentPane().add(txtNotaTrabalho);
        txtNotaTrabalho.setBounds(130, 90, 80, 20);
        getContentPane().add(txtNotaParcial);
        txtNotaParcial.setBounds(130, 120, 80, 20);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("RGM:");
        jLabel5.setMaximumSize(new java.awt.Dimension(43, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(43, 14));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 40, 100, 14);
        getContentPane().add(txtRgm);
        txtRgm.setBounds(130, 30, 90, 20);

        jButton1.setText("Consultar Aluno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 30, 130, 23);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(240, 190, 80, 23);

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btnInserir);
        btnInserir.setBounds(70, 190, 63, 23);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(140, 190, 73, 23);

        lblMensagem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(lblMensagem);
        lblMensagem.setBounds(10, 240, 430, 40);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(330, 190, 80, 23);

        setSize(new java.awt.Dimension(462, 323));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        AlunoBean nota1 = new AlunoBean();
        String resultado = "";
        if (txtRgm.getText().equals("")) {
            lblMensagem.setText("Preencha o campo RGM");
        } else if (txtNome.getText().equals("")) {
            lblMensagem.setText("Preencha o campo nome");
        } else if (txtNotaTrabalho.getText().equals("")) {
            lblMensagem.setText("Prelencha o campo Nota1");
        } else if (txtNotaParcial.getText().equals("")) {
            lblMensagem.setText("Preencha o campo Nota2");
        } else {
        AlunoDao inserir = new AlunoDao();
        resultado = inserir.gravarAluno(montaAluno());

            txtNotaA1.setText(nota1.calculaNotaA1(Float.parseFloat (txtNotaTrabalho.getText()), Float.parseFloat(txtNotaParcial.getText())));
            if (resultado == "OK") {
                lblMensagem.setText("Aluno Gravado com Sucesso");
            } else {
                lblMensagem.setText("" + resultado);
            }
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (txtRgm.getText().equals("")) {
            lblMensagem.setText("Preencha o campo RGM");
        }else{
        AlunoDao alterar = new AlunoDao();
        String resul = alterar.alterarAluno(montaAluno());
        if(resul.equals("OK")){
            JOptionPane.showMessageDialog(null,"Alterado com Sucesso");
        }else{
            JOptionPane.showMessageDialog(null,resul);
        }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
                if (txtRgm.getText().equals("")) {
            lblMensagem.setText("Preencha o RGM");
        } else {
            Aluno aluno = new AlunoDao().getAluno(txtRgm.getText());
            if (aluno == null) {
                txtNome.setText("");
                txtNotaTrabalho.setText("");
                txtNotaParcial.setText("");
                lblMensagem.setText("Aluno Não Encontrado");
            } else {
                txtNome.setText(aluno.getNome());
                txtNotaTrabalho.setText(aluno.getNotaTrabalho()+ "");
                txtNotaParcial.setText(aluno.getNotaProvaParcial()+ "");
                lblMensagem.setText("Aluno Encontrado");
            }
            }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
            AlunoDao excluir = new AlunoDao();
        String resul = excluir.excluirAluno(montaAluno());
        if(resul.equals("OK")){
            JOptionPane.showMessageDialog(null,"Excluído com Sucesso");
        }else{
            JOptionPane.showMessageDialog(null,resul);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmListagem tela = new frmListagem();
        tela.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNotaA1;
    private javax.swing.JTextField txtNotaParcial;
    private javax.swing.JTextField txtNotaTrabalho;
    private javax.swing.JTextField txtRgm;
    // End of variables declaration//GEN-END:variables
}

//** /**
 /* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

public class frmPrincipal extends javax.swing.JFrame {

   
     * Creates new form frmPrincipal
     */
  /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//

///
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


