/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Frete;
import java.util.Set;
import bean.CalculaFrete;

/**
 *
 * @author willi
 */
public class CalculoF extends javax.swing.JInternalFrame {

    /**
     * Creates new form CalculoF
     */
    public CalculoF() {
        initComponents();
    }

    public Frete montaFrete() {
        Frete f = new Frete();
        String estado;
        estado = cmbEstado.getItemAt(cmbEstado.getSelectedIndex()).toString();
           /*
        if (cmbEstado.getSelectedItem().equals("São Paulo")) {
            f.setEstado("São Paulo");
        } else if (cmbEstado.getSelectedItem().equals("Rio de Janeiro")) {
            f.setEstado("Rio de Janeiro");
        }
        if (cmbEstado.getSelectedItem().equals("Minas Gerais")) {
            f.setEstado("Minas Gerais");
        } else if (cmbEstado.getSelectedItem().equals("Espirito Santo")) {
            f.setEstado("Espirito Santo");
        }*/
        f.setEstado(estado);
        f.setPeso(Float.parseFloat(txtPeso.getText()));

        if (chkSedex.isSelected() == true) {
            f.setTipoEncomenda("Sedex");
        } else if (chkAR.isSelected() == true) {
            f.setTipoEncomenda("AR");
        }
        if (chkSimples.isSelected() == true) {
            f.setTipoEncomenda("Simples");
        } else if (chkDinheiro.isSelected() == true) {
            f.setPagamento("Dinheiro");
        }
        if (chkCheque.isSelected() == true) {
            f.setPagamento("Cheque");
        } else if (chkCartaoDeCredito.isSelected() == true) {
            f.setPagamento("Cartão de Credito");
        }
        return f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipoDeEncomenda = new javax.swing.ButtonGroup();
        btnGroupPagamento = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtTotalAPagar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        chkAR = new javax.swing.JRadioButton();
        chkSimples = new javax.swing.JRadioButton();
        chkDinheiro = new javax.swing.JRadioButton();
        chkCheque = new javax.swing.JRadioButton();
        chkCartaoDeCredito = new javax.swing.JRadioButton();
        chkSedex = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel1BackGround = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel2.setText("Pagamento:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 210, 240, 20);

        cmbEstado.setBackground(new java.awt.Color(255, 204, 204));
        cmbEstado.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "São Paulo", "Rio de Janeiro", "Minas Gerais", "Espirito Santo" }));
        getContentPane().add(cmbEstado);
        cmbEstado.setBounds(30, 80, 230, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel3.setText("Total a Pagar:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 50, 210, 20);

        txtTotalAPagar.setBackground(new java.awt.Color(204, 255, 204));
        txtTotalAPagar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        getContentPane().add(txtTotalAPagar);
        txtTotalAPagar.setBounds(290, 80, 230, 30);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel4.setText("Peso:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 90, 20);

        btnGroupTipoDeEncomenda.add(chkAR);
        chkAR.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        chkAR.setText("A.R");
        chkAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkARActionPerformed(evt);
            }
        });
        getContentPane().add(chkAR);
        chkAR.setBounds(40, 290, 130, 35);

        btnGroupTipoDeEncomenda.add(chkSimples);
        chkSimples.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        chkSimples.setText("Simples");
        getContentPane().add(chkSimples);
        chkSimples.setBounds(40, 330, 130, 35);

        btnGroupPagamento.add(chkDinheiro);
        chkDinheiro.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        chkDinheiro.setText("Dinheiro");
        getContentPane().add(chkDinheiro);
        chkDinheiro.setBounds(290, 250, 130, 35);

        btnGroupPagamento.add(chkCheque);
        chkCheque.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        chkCheque.setText("Cheque");
        getContentPane().add(chkCheque);
        chkCheque.setBounds(290, 290, 130, 35);

        btnGroupPagamento.add(chkCartaoDeCredito);
        chkCartaoDeCredito.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        chkCartaoDeCredito.setText("Cartão de Crédito");
        getContentPane().add(chkCartaoDeCredito);
        chkCartaoDeCredito.setBounds(290, 330, 220, 35);

        btnGroupTipoDeEncomenda.add(chkSedex);
        chkSedex.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        chkSedex.setText("Sedex 10");
        getContentPane().add(chkSedex);
        chkSedex.setBounds(40, 250, 130, 35);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel5.setText("Tipo de Encomenda:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 210, 240, 20);

        btnFechar.setBackground(new java.awt.Color(255, 204, 204));
        btnFechar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnFechar.setText("Fechar");
        getContentPane().add(btnFechar);
        btnFechar.setBounds(340, 380, 170, 40);

        btnCalcular.setBackground(new java.awt.Color(255, 204, 204));
        btnCalcular.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(40, 380, 170, 40);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel6.setText("Estado:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 50, 90, 20);

        txtPeso.setBackground(new java.awt.Color(255, 204, 204));
        txtPeso.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        getContentPane().add(txtPeso);
        txtPeso.setBounds(30, 160, 230, 30);

        jLabel1BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cor.jpg"))); // NOI18N
        getContentPane().add(jLabel1BackGround);
        jLabel1BackGround.setBounds(-10, 0, 570, 460);

        setBounds(0, 0, 559, 503);
    }// </editor-fold>//GEN-END:initComponents

    private void chkARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkARActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        /*
        double encomenda = new CalculaFrete().CalculandoTipoEncomenda(montaFrete());
        double frete = new CalculaFrete().CalculandoTipoEncomenda(montaFrete());
        double peso = new CalculaFrete().PegandoPeso(montaFrete());

        double tipoPagamento = new CalculaFrete().FormaDePagamento(montaFrete());
        double total = 0;
        total = (peso * encomenda + frete) * tipoPagamento;
        txtTotalAPagar.setText("R$: " + total);
         */

        double frete = new CalculaFrete().CalculandoTipoEncomenda(montaFrete());
        //total = (peso * frete + encomenda) * tipoPagamento;
        txtTotalAPagar.setText("R$: " + frete);

    }//GEN-LAST:event_btnCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnFechar;
    private javax.swing.ButtonGroup btnGroupPagamento;
    private javax.swing.ButtonGroup btnGroupTipoDeEncomenda;
    private javax.swing.JRadioButton chkAR;
    private javax.swing.JRadioButton chkCartaoDeCredito;
    private javax.swing.JRadioButton chkCheque;
    private javax.swing.JRadioButton chkDinheiro;
    private javax.swing.JRadioButton chkSedex;
    private javax.swing.JRadioButton chkSimples;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1BackGround;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTotalAPagar;
    // End of variables declaration//GEN-END:variables
}
